apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  namespace: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
      - name: azurite
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
        - containerPort: 10000
        - containerPort: 10001
        - containerPort: 10002
---
apiVersion: v1
kind: Service
metadata:
  name: azurite
  namespace: tech-challenge
spec:
  type: NodePort
  selector:
    app: azurite
  ports:
    - name: blob
      port: 10000
      targetPort: 10000
      nodePort: 31000
    - name: queue
      port: 10001
      targetPort: 10001
      nodePort: 31001
    - name: table
      port: 10002
      targetPort: 10002
      nodePort: 31002