services:
  techchallangeapi:
    image: fiap-tech-tech-challange
    container_name: fiap-tech-tech-challange
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    stdin_open: true    # Permite interação com o contêiner (modo interativo)
    tty: true           # Terminal interativo
    networks:
      - monitoring

  ocelotgatewayapi:
    image: ocelot-gateway
    container_name: ocelot-gateway
    build:
      context: ./OcelotGateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - techchallangeapi
    networks:
      - monitoring
      
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5672:5672"   # Porta padrão do RabbitMQ
      - "15672:15672" # Porta do painel de administração do RabbitMQ
    depends_on:
      - techchallangeapi
    networks: 
      - monitoring

  prometheus:
    image: prometheus
    container_name: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 9090:9090
    depends_on:
      - techchallangeapi
    networks:
      - monitoring
    volumes: 
      - './prometheus/data:/data'

  grafana:
    image: grafana
    container_name: grafana
    build:
      context: ./grafana
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks: 
      - monitoring

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-storage
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  azurefunction:
    image: azure-function
    container_name: azure-function
    build:
      context: ./AzureFunction
      dockerfile: Dockerfile
    ports:
      - "7071:80"
    environment:
      - RabbitMQConnection=amqp://guest:guest@rabbitmq:5672/
      - WEBSITES_INCLUDE_CLOUD_CERTS=true
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - FUNCTIONS_EXTENSION_VERSION=~4
      - Grpc__ChannelOptions__HttpHandlerType=HttpClientHandler
      - Grpc__ChannelOptions__HttpClientType=HttpClient
      - Grpc__ChannelOptions__MaxReceiveMessageSize=4194304
      - Grpc__ChannelOptions__MaxSendMessageSize=4194304
    depends_on:
      - techchallangeapi
      - ocelotgatewayapi
      - grafana
      - rabbitmq
      - azurite
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
