apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: config-volume
          mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
          subPath: datasource.yaml
        - name: dashboards-volume
          mountPath: /etc/grafana/provisioning/dashboards/dashboard.yaml
          subPath: dashboard.yaml
        - name: dashboard-volume
          mountPath: /var/lib/grafana/dashboards/techchallenge.json
          subPath: techchallenge.json
      volumes:
      - name: config-volume
        configMap:
          name: grafana-datasource
      - name: dashboards-volume
        configMap:
          name: grafana-dashboards
      - name: dashboard-volume
        configMap:
          name: grafana-dashboard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: tech-challenge
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        access: proxy
        isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: tech-challenge
data:
  dashboard.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard
  namespace: tech-challenge
data:
  techchallenge.json: |
    {
      "title": "ASP.NET Core Metrics",
      "uid": "techchallenge-dashboard",
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "panels": [
        {
          "title": "Requests Duration",
          "type": "timeseries",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
              "legendFormat": "p50",
              "refId": "A"
            },
            {
              "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
              "legendFormat": "p95",
              "refId": "B"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          }
        }
      ],
      "templating": {
        "list": [
          {
            "name": "job",
            "type": "query",
            "datasource": "Prometheus",
            "query": "label_values(http_server_active_requests, job)",
            "refresh": 2
          },
          {
            "name": "instance",
            "type": "query",
            "datasource": "Prometheus",
            "query": "label_values(http_server_active_requests{job=~\"$job\"}, instance)",
            "refresh": 2
          }
        ]
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: tech-challenge
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300