apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotgatewayapi
  namespace: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelotgatewayapi
  template:
    metadata:
      labels:
        app: ocelotgatewayapi
    spec:
      containers:
      - name: ocelotgatewayapi
        image: cabxavier/ocelot-gateway-api
        ports:
        - containerPort: 5001
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5001"
---
apiVersion: v1
kind: Service
metadata:
  name: ocelotgatewayapi
  namespace: tech-challenge
spec:
  type: NodePort
  selector:
    app: ocelotgatewayapi
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30001