apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallangeapi
  namespace: tech-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techchallangeapi
  template:
    metadata:
      labels:
        app: techchallangeapi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: techchallangeapi
        image: cabxavier/fiap-techchallange-api
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: techchallangeapi
  namespace: tech-challenge
spec:
  type: NodePort
  selector:
    app: techchallangeapi
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
