global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'techchallangeapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          application: techchallangeapi