apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurefunction
  namespace: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurefunction
  template:
    metadata:
      labels:
        app: azurefunction
    spec:
      containers:
      - name: azurefunction
        image: cabxavier/azure-function
        ports:
        - containerPort: 80
        env:
        - name: RabbitMQConnection
          value: "amqp://guest:guest@rabbitmq:5672/"
---
apiVersion: v1
kind: Service
metadata:
  name: azurefunction
  namespace: tech-challenge
spec:
  type: NodePort
  selector:
    app: azurefunction
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080